# Practical Session 7: `numpy`

### 1. Basic arrays

Firstly import `numpy` using alais `np`, this only needs to be done *once* per notebook or Python script

In [ ]:
import numpy as np

Create arrays of various dimensions:

- A scalar (0D)
- A vector of 5 elements (1D)

- A 3x4  2D array (matrix)

- A 2x3x2 3D tensor

Print the shape of each

In [4]:
import numpy as np

# Scalar (0D)
scalar = np.array(42)
print("Scalar shape:", scalar.shape)

# Vector of 5 elements (1D)
vector = np.array([1, 2, 3, 4, 5])
print("Vector shape:", vector.shape)

# 3x4 2D array (matrix)
matrix = np.arange(12).reshape(3, 4)
print("Matrix shape:", matrix.shape)

# 2x3x2 3D tensor
tensor = np.arange(12).reshape(2, 3, 2)
print("Tensor shape:", tensor.shape)

Scalar shape: ()
Vector shape: (5,)
Matrix shape: (3, 4)
Tensor shape: (2, 3, 2)


### 2. Creating arrays

Create the following arrays:

- A 6×6 array filled with zeros

- A 2×5 array filled with the number 7

- A linearly spaced 1D array from -1 to 1 with 9 elements

- A 3×3 array with numbers from 0 to 8 using arange

- A 1D array with values [1, 4, 9, 16, 25] generated using vectorised operations

In [3]:
# 6×6 array filled with zeros
zeros_array = np.zeros((6, 6))
print("6x6 zeros array:\n", zeros_array)

# 2×5 array filled with the number 7
sevens_array = np.full((2, 5), 7)
print("\n2x5 array filled with 7:\n", sevens_array)

# Linearly spaced 1D array from -1 to 1 with 9 elements
linspace_array = np.linspace(-1, 1, 9)
print("\nLinearly spaced array from -1 to 1 with 9 elements:\n", linspace_array)

# 3×3 array with numbers from 0 to 8 using arange
arange_array = np.arange(9).reshape((3, 3))
print("\n3x3 array from 0 to 8:\n", arange_array)

# 1D array with values [1, 4, 9, 16, 25] using vectorized operations
x = np.arange(1, 6)
squares_array = x**2
print("\n1D array with squares of 1 to 5:\n", squares_array)

6x6 zeros array:
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

2x5 array filled with 7:
 [[7 7 7 7 7]
 [7 7 7 7 7]]

Linearly spaced array from -1 to 1 with 9 elements:
 [-1.   -0.75 -0.5  -0.25  0.    0.25  0.5   0.75  1.  ]

3x3 array from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

1D array with squares of 1 to 5:
 [ 1  4  9 16 25]


Create a 4×4 array of random floats between 0 and 1. Then:

- Multiply all values by 100 and round them

- Set all values above 70 to 70

In [5]:
# Create a 4x4 array of random floats between 0 and 1
arr = np.random.rand(4, 4)

# Multiply all values by 100 and round them
arr = np.round(arr * 100)

# Set all values above 70 to 70
arr[arr > 70] = 70

print(arr)


[[70. 22. 70. 44.]
 [65. 32. 70. 70.]
 [70. 50.  1. 32.]
 [70. 70. 53. 70.]]


### 3. Reshaping and Indexing

You are given this flat array:

```python
arr = np.arange(24)
```
Reshape it to a 3×2×4 array

In [6]:
arr = np.arange(24)
reshaped_arr = arr.reshape((3, 2, 4))
print(reshaped_arr)


[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


Extract:

- The 2nd block (index 1)

- The last row of the first block

- The element at position `[2, 1, 3]`



In [7]:
# The 2nd block (index 1)
second_block = reshaped_arr[1]
print("Second block (index 1):")
print(second_block)

# The last row of the first block (index 0)
last_row_first_block = reshaped_arr[0, -1]
print("\nLast row of the first block:")
print(last_row_first_block)

# The element at position [2, 1, 3]
element_2_1_3 = reshaped_arr[2, 1, 3]
print("\nElement at position [2, 1, 3]:")
print(element_2_1_3)

Second block (index 1):
[[ 8  9 10 11]
 [12 13 14 15]]

Last row of the first block:
[4 5 6 7]

Element at position [2, 1, 3]:
23


Flatten the full array

In [8]:
flattened = reshaped_arr.flatten()
print(flattened)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


### 4. Efficiency

Generate an array of 1000000 random numbers between 0 and 10. Each reading should then be adjusted by this set of rules:

- If the value is less than 2, square it.

- If it's between 2 and 8 (inclusive), take the square root.

- If it's above 8, set it to 10.

Use a loop to make these changes. Time how long this takes by
```python
import time
t_start = time.time()

# Put loop here

t_end = time.time()

print(f'This calculation took {t_end-t_start} seconds')
```

In [11]:
import time

# Generate the same random array for both methods
np.random.seed(0)
arr_loop = np.random.uniform(0, 10, 1000000)
arr_vec = arr_loop

# Loop method (re-run for timing)
t_start = time.time()
for i in range(len(arr_loop)):
    if arr_loop[i] < 2:
        arr_loop[i] = arr_loop[i] ** 2
    elif 2 <= arr_loop[i] <= 8:
        arr_loop[i] = arr_loop[i] ** 0.5
    else:
        arr_loop[i] = 10
t_end = time.time()
print(f"Loop calculation took {t_end - t_start:.4f} seconds")


Loop calculation took 0.2648 seconds


Now use boolean masking and `numpy` vectorised operations (no loops!) to achieve the same result, and time it again. Confirm the results using both techniques are the same (or very close) using `np.allclose`.

In [12]:
# Generate the same random array for both methods
arr_loop = np.random.uniform(0, 10, 1000000)
arr_vec = arr_loop

# Loop method (re-run for timing)
t_start = time.time()
for i in range(len(arr_loop)):
    if arr_loop[i] < 2:
        arr_loop[i] = arr_loop[i] ** 2
    elif 2 <= arr_loop[i] <= 8:
        arr_loop[i] = arr_loop[i] ** 0.5
    else:
        arr_loop[i] = 10
t_end = time.time()
print(f"Loop calculation took {t_end - t_start:.4f} seconds")

# Vectorized method
t_start = time.time()
mask1 = arr_vec < 2
mask2 = (arr_vec >= 2) & (arr_vec <= 8)
mask3 = arr_vec > 8

arr_vec[mask1] = arr_vec[mask1] ** 2
arr_vec[mask2] = np.sqrt(arr_vec[mask2])
arr_vec[mask3] = 10
t_end = time.time()
print(f"Vectorized calculation took {t_end - t_start:.4f} seconds")

# Confirm results are close
print("Results are close:", np.allclose(arr_loop, arr_vec))


Loop calculation took 0.2699 seconds
Vectorized calculation took 0.0229 seconds
Results are close: True


### 5. Statistics in arrays

You have this data:

```python
data = np.array([[1.2, 3.5, 2.1],
                 [4.4, 5.1, 0.5],
                 [3.3, 3.3, 3.3]])

```
- Compute the mean and standard deviation of each row

- Compute the column-wise sum

- Identify the index of the maximum value in the whole array

- Normalize each row to have a maximum of 1

In [13]:
data = np.array([[1.2, 3.5, 2.1],
                 [4.4, 5.1, 0.5],
                 [3.3, 3.3, 3.3]])

# Mean and std dev of each row
row_means = np.mean(data, axis=1)
row_stds = np.std(data, axis=1)

# Column-wise sum
col_sums = np.sum(data, axis=0)

# Index of maximum value in the whole array (flattened index)
max_index_flat = np.argmax(data)
# Convert flattened index to 2D index (row, col)
max_index_2d = np.unravel_index(max_index_flat, data.shape)

# Normalize each row to have max of 1
row_maxes = np.max(data, axis=1, keepdims=True)
normalized_data = data / row_maxes

print("Row means:", row_means)
print("Row std devs:", row_stds)
print("Column sums:", col_sums)
print("Index of max value (flattened):", max_index_flat)
print("Index of max value (2D):", max_index_2d)
print("Normalized data:\n", normalized_data)


Row means: [2.26666667 3.33333333 3.3       ]
Row std devs: [9.46337971e-01 2.02374790e+00 4.44089210e-16]
Column sums: [ 8.9 11.9  5.9]
Index of max value (flattened): 4
Index of max value (2D): (1, 1)
Normalized data:
 [[0.34285714 1.         0.6       ]
 [0.8627451  1.         0.09803922]
 [1.         1.         1.        ]]


### 6. Matrix Operations

Let:

```python
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[2, 0],
              [1, 2]])
```

Compute:

- A + B

- A × B (matrix product)

- Transpose of A

- Inverse of B

- Eigenvalues and eigenvectors of A

- Norm of A

In [14]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[2, 0],
              [1, 2]])

# A + B
sum_AB = A + B

# A × B (matrix multiplication)
prod_AB = A @ B  # or np.dot(A, B)

# Transpose of A
transpose_A = A.T

# Inverse of B
inv_B = np.linalg.inv(B)

# Eigenvalues and eigenvectors of A
eigvals, eigvecs = np.linalg.eig(A)

# Norm of A (Frobenius by default)
norm_A = np.linalg.norm(A)

print("A + B =\n", sum_AB)
print("A × B =\n", prod_AB)
print("Transpose of A =\n", transpose_A)
print("Inverse of B =\n", inv_B)
print("Eigenvalues of A =", eigvals)
print("Eigenvectors of A =\n", eigvecs)
print("Norm of A =", norm_A)


A + B =
 [[3 2]
 [4 6]]
A × B =
 [[ 4  4]
 [10  8]]
Transpose of A =
 [[1 3]
 [2 4]]
Inverse of B =
 [[ 0.5   0.  ]
 [-0.25  0.5 ]]
Eigenvalues of A = [-0.37228132  5.37228132]
Eigenvectors of A =
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Norm of A = 5.477225575051661


### 7. Estimating $\pi$ using Monte Carlo integration

Imagine a square with side length 2 centered at the origin. Inside it, there's a circle of radius 1, also centered at the origin.

If you randomly throw $n$ darts at this square, the fraction that lands inside the circle $n_\mathrm{circle}$ is roughly equal to the area of the circle $A_\mathrm{circle}$ divided by the area of the square $A_\mathrm{square}$:

$$
\frac{n}{n_{\mathrm{circle}}} = \frac{A_\mathrm{square}}{A_{\mathrm{circle}}}
$$

With somem rearranging, we can therefore use this fraction to estimate $\pi$.

Task:

- Generate n random points in the square `[-1,1] x [-1, 1]`

- Count how many fall within the unit circle

- Use the ratio to estimate $\pi$

In [16]:
def estimate_pi(n):
    # Generate n random points in [-1,1] x [-1,1]
    x = np.random.uniform(-1, 1, n)
    y = np.random.uniform(-1, 1, n)
    
    # Calculate distance from origin
    dist = np.sqrt(x**2 + y**2)
    
    # Count points inside the unit circle
    inside_circle = np.sum(dist <= 1)
    
    # Estimate pi using ratio of points inside circle vs total points
    pi_estimate = 4 * inside_circle / n
    
    return pi_estimate

# Example usage:
n_points = 1000000
pi_approx = estimate_pi(n_points)
print(f"Estimated π after {n_points} points: {pi_approx:.6f}")


Estimated π after 1000000 points: 3.141176


If not already, turn this code into a function `estimate_pi(n)`, and check the error between your estimation and the true value of $\pi$ for $n = 10, 100, 1000, 10000, 100000, 1000000$

In [17]:
# Values of n to test
n_values = [10, 100, 1000, 10000, 100000, 1000000]

print("n\tEstimate\tError")
for n in n_values:
    pi_est = estimate_pi(n)
    error = abs(np.pi - pi_est)
    print(f"{n}\t{pi_est:.6f}\t{error:.6f}")

n	Estimate	Error
10	4.000000	0.858407
100	3.200000	0.058407
1000	3.148000	0.006407
10000	3.171600	0.030007
100000	3.146240	0.004647
1000000	3.140752	0.000841


### 8. Simulating Particle Collisions in 1D

You have a stream of particles moving along a line. Each particle has a position and velocity.

- Positions and velocities are stored in two NumPy arrays of length N.

- At each timestep, particles move according to their velocity.

- If two particles collide (positions become equal or cross), they exchange velocities.

Initialize arrays for N=10 particles with random positions between 0 and 10 and velocities between -1 and 1.


In [19]:
N = 10
positions = np.random.uniform(0, 10, N)
velocities = np.random.uniform(-1, 1, N)

print("Initial positions:", positions)
print("Initial velocities:", velocities)

Initial positions: [1.15696432 6.34529448 6.75810624 6.17600981 2.77919186 9.51095159
 5.47040462 6.58322315 0.76833653 7.15122412]
Initial velocities: [ 0.20433008 -0.07456726 -0.04820047  0.08374808 -0.06991769  0.90749464
 -0.88846144  0.99183965 -0.82052696  0.7770196 ]


Write a loop that advances the system by 100 timesteps:

- Update positions by adding velocity.

- Check for collisions by comparing positions.

- Swap velocities of colliding particles.

After the loop, report the final positions and velocities.


In [21]:
N = 10
positions = np.random.uniform(0, 10, N)
velocities = np.random.uniform(-1, 1, N)

timesteps = 100

for _ in range(timesteps):
    # Update positions
    positions += velocities
    
    # Check collisions: compare every pair of particles
    for i in range(N):
        for j in range(i + 1, N):
            # If particles have crossed or are at the same position
            # i.e. the positions have overlapped or passed each other
            if (positions[i] - positions[j]) * (positions[i] - velocities[i] - (positions[j] - velocities[j])) <= 0:
                # Swap velocities
                velocities[i], velocities[j] = velocities[j], velocities[i]

print("Final positions:", positions)
print("Final velocities:", velocities)


Final positions: [ 60.49569995  -3.35718073  -3.2801303   61.17167622  60.69132969
 -49.30730158  -3.80623492 -49.51140429 -48.94662064  -3.52453213]
Final velocities: [ 0.8736018  -0.68494723 -0.58169338  0.11940147  0.73756234 -0.02784459
  0.50707899 -0.56411711 -0.94845     0.23979985]


### 9. Analysing Projectile Motion Data

You have experimental data from a projectile motion experiment: vertical position $y$ measured over time intervals of 0.1s in the data file `projectile_data.csv`.

Firstly load the data from `projectile_data.csv` into a numpy array.

In [22]:
# Load data from CSV file (assuming one column for vertical position y)
data = np.loadtxt('projectile_data.csv', delimiter=',')

print(data)


[0.00000000e+00 9.90190000e-02 1.97057000e-01 2.94114000e-01
 3.90190000e-01 4.85285000e-01 5.79399000e-01 6.72532000e-01
 7.64684000e-01 8.55855000e-01 9.46045000e-01 1.03525400e+00
 1.12348200e+00 1.21072900e+00 1.29699500e+00 1.38228000e+00
 1.46658400e+00 1.54990700e+00 1.63224900e+00 1.71361000e+00
 1.79399000e+00 1.87338900e+00 1.95180700e+00 2.02924400e+00
 2.10570000e+00 2.18117500e+00 2.25566900e+00 2.32918200e+00
 2.40171400e+00 2.47326500e+00 2.54383500e+00 2.61342400e+00
 2.68203200e+00 2.74965900e+00 2.81630500e+00 2.88197000e+00
 2.94665400e+00 3.01035700e+00 3.07307900e+00 3.13482000e+00
 3.19558000e+00 3.25535900e+00 3.31415700e+00 3.37197400e+00
 3.42881000e+00 3.48466500e+00 3.53953900e+00 3.59343200e+00
 3.64634400e+00 3.69827500e+00 3.74922500e+00 3.79919400e+00
 3.84818200e+00 3.89618900e+00 3.94321500e+00 3.98926000e+00
 4.03432400e+00 4.07840700e+00 4.12150900e+00 4.16363000e+00
 4.20477000e+00 4.24492900e+00 4.28410700e+00 4.32230400e+00
 4.35952000e+00 4.395755

Create a time array for this data, where each time corresponds to the position in `projectile_data.csv`.

In [23]:
# Number of data points
n_points = data.shape[0]

# Create time array from 0 to (n_points-1)*0.1 with step 0.1
time = np.arange(n_points) * 0.1

print(time)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9 10.  10.1 10.2 10.3 10.4 10.5 10.6 10.7 10.8 10.9 11.  11.1
 11.2 11.3 11.4 11.5 11.6 11.7 11.8 11.9 12.  12.1 12.2 12.3 12.4 12.5
 12.6 12.7 12.8 12.9 13.  13.1 13.2 13.3 13.4 13.5 13.6 13.7 13.8 13.9
 14.  14.1 14.2 14.3 14.4 14.5 14.6 14.7 14.8 14.9 15.  15.1 15.2 15.3
 15.4 15.5 15.6 15.7 15.8 15.9 16.  16.1 16.2 16.3 16.4 16.5 16.6 16.7
 16.8 16.9 17.  17.1 17.2 17.3 17.4 17.5 17.6 17.7 17.8 17.9 18.  18.1
 18.2 18.3 18.4 18.5 18.6 18.7 18.8 18.9 19.  19.1 19.2 19.3 19.4 19.5
 19.6 

Calculate the velocity and acceleration at each time step using the finite difference method, i.e.
$$
v_i = \frac{y_{i+1} - y_i}{t_{i+1} - t_i} \\

a_i = \frac{v_{i+1} - v_i}{t_{i+1} - t_i}
$$
Find the maximum height reached by the projectile, and the time the projectile hits the ground the first time after launch.

In [24]:
# Calculate velocity using forward differences
velocity = (data[1:] - data[:-1]) / (time[1:] - time[:-1])

# Calculate acceleration similarly from velocity
acceleration = (velocity[1:] - velocity[:-1]) / (time[2:] - time[1:-1])

# Maximum height and corresponding time
max_height = np.max(data)
max_height_index = np.argmax(data)
time_max_height = time[max_height_index]

print(f"Maximum height: {max_height:.3f} meters at time {time_max_height:.3f} s")

# Find when projectile hits ground (y <= 0) for the first time after launch
# We'll look for the first index where data goes <= 0 after the first point
ground_indices = np.where(data <= 0)[0]

# Ignore the very first if it starts at 0 (launch)
ground_indices_after_launch = ground_indices[ground_indices > 0]

if ground_indices_after_launch.size > 0:
    first_ground_index = ground_indices_after_launch[0]
    time_ground = time[first_ground_index]
    print(f"Projectile hits the ground at time: {time_ground:.3f} s")
else:
    print("Projectile does not hit the ground within the data range.")


Maximum height: 5.047 meters at time 10.100 s
Projectile hits the ground at time: 20.300 s


Save a new `numpy` array with columns for time, position, velocity and acceleration in the file `projectile_analysis.csv`. You will need to trim the data to be the length of the acceleration array.

In [25]:
# To align lengths, we need to trim or pad arrays because
# velocity has length len(data) - 1
# acceleration has length len(data) - 2

# We'll trim all arrays to the shortest length, which is acceleration's length + 2
n = len(acceleration)  # length of acceleration

# Trim arrays accordingly:
time_trimmed = time[:n]
position_trimmed = data[:n]
velocity_trimmed = velocity[:n]
acceleration_trimmed = acceleration  # already length n

# Stack columns horizontally
result = np.column_stack((time_trimmed, position_trimmed, velocity_trimmed, acceleration_trimmed))

# Save to CSV with headers
header = "time,position,velocity,acceleration"
np.savetxt("projectile_analysis.csv", result, delimiter=",", header=header, comments='')
